# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    #pool:
    #  vmImage: ubuntu-latest
    steps:
    #- task: Bash@3
    #  displayName: Docker login
    #  inputs:
    #    targetType: 'inline'
    #    script: 'sudo docker login $(NexusRepoURL) --username $(Username) --password $(Password)'
    - task: Bash@3
      displayName: List SourcesDirectory
      inputs:
        targetType: 'inline'
        script: ls $(Build.SourcesDirectory)
    - task: Bash@3
      displayName: Show docker-compose.yml content
      inputs:
        targetType: 'inline'
        script: cat '$(Build.SourcesDirectory)/src/dotnet-6.0/Web/docker-compose.yml'
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'omid.ddns.net-docker-hosted'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
