# Variable 'SqlPassword' was defined in the Variables tab

trigger: none

jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Win19-Vs19
  steps:
  - checkout: self
    clean: true
  - task: RedgateSqlChangeAutomationBuild@4
    displayName: Build SQL Change Automation Project AdventureWorks2019
    inputs:
      sqlProj: db/AdventureWorks2019/AdventureWorks2019.sqlproj
      packageName: AdventureWorks2019
      tempServerTypeBuild: sqlServer
      tempServerNameBuild: .\Sql2019
      tempDatabaseNameBuild: AW2019
      tempTrustServerCertificateBuild: true
      authMethodBuild: sqlServerAuth
      usernameBuild: sa
      passwordBuild: $(SqlPassword)
      nugetPackageVersionUseBuildId: true
