# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'omid.ddns.net-docker-hosted'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          dev-$(Build.BuildNumber)
          latest
#    - task: Docker@2
#      displayName: Build an image
#      inputs:
#        containerRegistry: 'omid.ddns.net-docker-hosted'
#        command: 'build'
#        Dockerfile: '**/Dockerfile'
#        tags: |
#          dev-$(Build.BuildNumber)
#          latest
