version: '3'
#networks:
  #network1:
  #  external: True
services:
  nginx-service:
    image: web:dev
    container_name: nginx-web-container
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=prod
    #volumes:
    #  - ./nginxhtml:/usr/share/nginx/html
    ports:
      - 8080:80
      - 8443:443
    #networks:
    #  - network1
