/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Temp_Table2]
(
[Id] [int] NOT NULL,
[Field1] [nchar] (10) NULL
)
GO
ALTER TABLE [dbo].[Temp_Table2] ADD CONSTRAINT [PK_Temp_Table2] PRIMARY KEY CLUSTERED ([Id])
GO
